name: Deep5mC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - pytorch 
  - pytorch-cuda
  - numpy
  - biopython
  - tqdm
  - scikit-learn
  - pandas
  - scipy
  - matplotlib